<a href="https://colab.research.google.com/github/eduardomtzchenoweth/curso_prepedeutico_CD/blob/main/intro_python_MtzChenoweth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/mcd-unison/material-programacion/blob/main/intro-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<p><img src="https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png" width="100">
</p>



# Curso Propedéutico en *Programación*

## Introducción a `python` resolviendo preguntas


**Julio Waissman Vilanova**



### Tipos

¿Cuales son los tipos de datos básicos? Revisa los tipos siguientes:

1. Tipos numéricos `int`, `float`, `complex`
2. Cadenas de caracteres
3. Tuplas
4. Listas
5. Diccionarios
6. Conjuntos

Da ejemplo de sobrecarga de operadores (en particular `+` y `*`)



In [ ]:
numero = 5
numero.__add__(5)
print(numero.__add__(5))
print(5 + 5)

numero = 4
numero.__mul__(3)
print(numero.__mul__(3))
print(4 * 3)

10
10
12
12


¿Que significa que unos tipos sean *mutables* y otros *inmutables*?

Realiza un pequeño programa donde quede claro lo que significa que un tipo de datos sea mutable, e ilustra el uso del método `copy.deepcopy()`.

### RESPUESTA A ***¿Que significa que unos tipos sean mutables y otros inmutables?***
Un tipo mutable son valores los cuales puedes modificar (listas, diccionarios), por otra parte, los inmutables son aquellos que una vez creados no se pueden modificar (enteros, cadenas).

In [ ]:
import copy
#MUTABLES
persona1 = {"nombre":"Miguel", "edad":30}
persona2 = persona1
persona2["nombre"]="Rodrigo"
print("MUTABLES".center(35,"*"))
print(persona1)
print(persona2)

#INMUTABLES
cadena1 = "Este valor no deberia de cambiar"
cadena2 = cadena1
cadena2 = "cambiando cadena..."
print("INMUTABLES".center(35,"*"))
print(cadena1)
print(cadena2)

#DEEPCOPY
persona1 = {"nombre":"Miguel", "edad":30}
persona2 = copy.deepcopy(persona1)
persona2["nombre"]="Rodrigo"
print("DEEPCOPY".center(35,"*"))
print(persona1)
print(persona2)

**************MUTABLES*************
{'nombre': 'Rodrigo', 'edad': 30}
{'nombre': 'Rodrigo', 'edad': 30}
*************INMUTABLES************
Este valor no deberia de cambiar
cambiando cadena...
**************DEEPCOPY*************
{'nombre': 'Miguel', 'edad': 30}
{'nombre': 'Rodrigo', 'edad': 30}


### *Comprehension* de listas, conjuntos y diccionarios

Escribe, en una sola linea, una expresión que genere una lista con todos los números enteros que se encuentran entre $1$ y $n$
que sean divisibles por $3$ y $7$ y que el dígito menos significativo del número sea $6$.

In [ ]:
n = 10_000
# Escribe aqui el *one linner*
print([x for x in range(1,10000,1) if x % 3 == 0 and x % 7 == 0 and x % 10 == 6])

[126, 336, 546, 756, 966, 1176, 1386, 1596, 1806, 2016, 2226, 2436, 2646, 2856, 3066, 3276, 3486, 3696, 3906, 4116, 4326, 4536, 4746, 4956, 5166, 5376, 5586, 5796, 6006, 6216, 6426, 6636, 6846, 7056, 7266, 7476, 7686, 7896, 8106, 8316, 8526, 8736, 8946, 9156, 9366, 9576, 9786, 9996]


### Funciones

Escribe una función que:

1. reciba una lista de elementos (letras, números, lo que sea),
2. cuente la ocurrencia de cada elemento en la lista,
3. devuelva las ocurrencias en forma de diccionario,
4. si imprime es True, imprima un histograma de ocurrencias, por ejemplo:

```python

lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]

d = funcion_ejemplo(lista, imprime = True)

1    		***** 	(5 -> 50%)
'a'  		***   	(3 -> 30%)
13		*	(1 -> 10%)
'hola'		*	(1 -> 10%)

```

In [ ]:
# Escribe la función aquí
def funcionContar(lista=[], imprime=False):
  hash = {}
  for x in lista:
    hash[x] = lista.count(x)
  if(imprime):
    for (key,val) in hash.items():
      print(f"{key}:\t{val * '*'}\t{val} -> {val/len(lista)*100}%")


In [ ]:
# Realiza pruebas aquí
lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]
d = funcionContar(lista, imprime = True)

1:	*****	5 -> 50.0%
a:	***	3 -> 30.0%
13:	*	1 -> 10.0%
hola:	*	1 -> 10.0%


Escribe una función que modifique un diccionario y regrese el diccionario modificado y una copia del original, donde cada entrada
del diccionario sea una lista de valores. Ten en cuenta que si una entrada del diccionario es de tipo mutable, al modificarlo en la
copia se modifica el original. Utiliza el modulo `copy` para evitar este problema. Ejemplo de la función:

```python
dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1, 'Pepe', 1, 'febrero')

print(dic1)
{'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}

print(dic2)
{'Pepe':[12, 'febrero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
```

In [ ]:
# Escribe la función fundicos aquí
import copy
def fundicos(dicToModify, entrada, dia=None, mes=None, año=None):
  dic = copy.deepcopy(dicToModify)
  if(dia): dic[entrada][0]=dia
  if(mes): dic[entrada][1]=mes
  if(año): dic[entrada][2]=año

  return [dicToModify,dic]


In [ ]:
# Realiza pruebas de fundicos aquí
dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1, 'Pepe', 1, 'febrero')

print(dic1)
print(f"Original:{dic2[0]}\nModificado:{dic2[1]}")

{'Pepe': [12, 'enero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}
Original:{'Pepe': [12, 'enero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}
Modificado:{'Pepe': [1, 'febrero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}


### Generadores

Escribe un generador que reciba una lista y genere todas las permutaciones que se puedan hacer con los elementos de la lista

In [ ]:
# Escribe aqui fun1

def permutaciones(lista):
    """
    Permutaciones de los elementos de una lista.

    Devuelve un generador con todas las permutaciones posibles de los elementos de la lista de entrada
    """
    #TODO: Implementar la función
    if(len(lista)==1): return [str(lista[0])]

    listaPermutacionesRecursiva = permutaciones(lista[1:])
    caracter = lista[0]
    listaPermutaciones = []
    for permutacion in listaPermutacionesRecursiva :
      for i in range(len(permutacion) + 1):
        listaPermutaciones.append(str(permutacion[:i]) + str(caracter) + str(permutacion[i:]))

    return listaPermutaciones



In [ ]:
# Realiza pruebas de fun2 aquí
for p in permutaciones(['a', 'b', 'c', 'd']):
    print(p)

abcd
bacd
bcad
bcda
acbd
cabd
cbad
cbda
acdb
cadb
cdab
cdba
abdc
badc
bdac
bdca
adbc
dabc
dbac
dbca
adcb
dacb
dcab
dcba


Ahora escribe una funcipn que reciba 4 digitos del 0 al 9, y devuelva una lista con todas las horas váidas que se puedan hacer con estos dígitos en forma de lista de strings con la forma `"HH:MM"`.

In [ ]:
def horas_validas(lista):
    """
    Docstring a comentar correctamente
    """
    return [(f"{int(permutacion[0])*10 + int(permutacion[1])}:{int(permutacion[2])*10 + int(permutacion[3])}") for permutacion in permutaciones(lista)
      if( int(permutacion[0])*10 + int(permutacion[1]) < 24 and int(permutacion[2])*10 + int(permutacion[3]) < 60)]

    #TODO: Implementar la función

Validando:

In [ ]:
aa = horas_validas([1,2,3,7])
print(aa)

['12:37', '21:37', '23:17', '13:27', '17:23', '17:32']


Escribe una función, lo más compacta posible, que escoja entre los 3 patrones ascii a continuación, e imprima en pantalla
el deseado, pero de dimensión $n$ ($n \ge 4$), toma en cuanta que para algunos valores de $n$ habrá
algún(os) patrones que no se puedan hacer.

```
          *             ++++           oooooooo
          **            ++++           ooo  ooo
          ***           ++++           oo    oo
          ****          ++++           o      o
          *****             ++++       o      o
          ******            ++++       oo    oo
          *******           ++++       ooo  ooo
          ********          ++++       oooooooo

```

In [ ]:
# Escribe aquí la función
def imprimir_patrones(patron,numero):
  if numero < 4: print("Necesita ser un numero mayor a 4")
  elif patron=="*":
    for x in range(numero+1):
      print("*" * x)
  elif patron=="+":
    for x in range(numero*2):
      if(numero <= x):
        print(" "*numero + "+"*numero)
      else:
        print("+" * numero)
  elif patron=="o":
    if(numero%2==0):
      spaces=0
      for x in range(numero, 0, -1):
        print("o"*x + "  "*spaces + "o"*x)
        spaces += 1

      spaces = numero - 1

      for x in range(1, numero+1, 1):
        print("o"*x + "  "*spaces + "o"*x)
        spaces -= 1
    else:
      print("Este patron se puede realizar unicamente con numeros pares")
  else:
    print("Seleccione una opcion valida (*, +, o)")



In [ ]:
#Realiza pruebas aquí
imprimir_patrones("o",4)
imprimir_patrones("+",5)
imprimir_patrones("*",6)

oooooooo
ooo  ooo
oo    oo
o      o
o      o
oo    oo
ooo  ooo
oooooooo
+++++
+++++
+++++
+++++
+++++
     +++++
     +++++
     +++++
     +++++
     +++++

*
**
***
****
*****
******


### Clases y objetos

Diseña una clase Matriz con las siguientes características:

1. Como inicialización de un objeto es necesario conocer $n$, $m$ y tipo. En caso de no proporcionar $m$ la matriz se asume cuadrada de $n \times n$. En caso de no proporcionar $n$ la matriz tendrá una dimensión de $1 \times 1$.
2. De no especificarse todos los elementos se inicializan a 0, a menos que exista un tipo especial ( `unos` o `diag` por el momento).
3. Implementa con sobrecarga la suma de matrices, la multiplicación de matrices y la multiplicación por un escalar.
4. Implementa como métodos eliminar columna y eliminar fila.   
5. Programa la representación visual de la matriz.
6. Ten en cuenta tambien el manejo de errores.


Ejemplo de uso:

```
>>> A = Matriz(n=3, m=4)

>>> print(A)
0 0 0 0
0 0 0 0
0 0 0 0

>>> A = A.quitafila(2)

>>> print(A)
0 0 0 0
0 0 0 0

>>> B = Matriz(4,4,'diag')

>>> print(B)
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1

>>> C = Matriz(4,1,'unos')

>>> print(C)
1
1
1
1

>>> D = 3 * B * C

>>> print(D)
3
3
3
3

>>> E = 3 * B + C
error "No seas menso, si no son de la misma dimensión las matrices no se pueden sumar"
```

In [ ]:
# Desarrolla aqui la clase
class Matriz:
  def __init__(self, n=None, m=None, tipo=None, array=None):
    self.n = n
    self.m = m
    self.tipo = tipo
    if(array != None):
      self.n = len(array)
      self.m = len(array[0])
      self.matriz = [[elemento for elemento in fila] for fila in array]
    elif(tipo == "diag"):
      if(self.n != self.m):
        raise TypeError("Diagonal no válida. Para poder hacer una diagonal tiene que ser una matriz cuadrada.")
      self.matriz = [[1 if indiceElemento==indiceFila else 0 for indiceElemento in range(m)] for indiceFila in range(n)]
    elif(tipo == "unos"):
      self.matriz = [[1 for _ in range(m)] for _ in range(n)]
    else:
      self.matriz = [[0 for _ in range(m)] for _ in range(n)]

  def __matriz_formateo(self):
    string = "\n"
    for fila in self.matriz:
      for elemento in fila:
        string += str(elemento) + " "
      string += "\n"
    return string

  def __matriz_mult(self,matriz1, matriz2=None, escalar=None):
    if(escalar!=None):
      return Matriz(array=[[elemento*escalar for elemento in filas] for filas in matriz1.matriz]);
    elif(matriz2 != None):
      resultado = [[0 for _ in range(matriz1.m)] for _ in range(matriz2.n)]
      for i in range(matriz1.n):
        for j in range(matriz2.m):
          for k in range(matriz1.m):
            resultado[i][j] += matriz1.matriz[i][k] * matriz2.matriz[k][j]

      return Matriz(array=resultado)

  def __verificar_matriz_mult(self,matriz1, matriz2):
    if(isinstance(matriz1, Matriz) and isinstance(matriz2, Matriz)):
        if(matriz1.m != matriz2.n):
          raise TypeError("Multiplicación no válida. Las columnas de la primera matriz no son iguales a las filas de la segunda matriz.")

  def __str__(self):
    return self.__matriz_formateo()

  def quitafila(self, numeroFila):
    del self.matriz[numeroFila-1]
    return self

  def quitacolumna(self, numerocolumna):
    for fila in range(0,self.n,1):
        del self.matriz[fila][numerocolumna-1]
    return self

  def __mul__(self,otro):
      self.__verificar_matriz_mult(self,otro)
      if(isinstance(otro, int)):
        return self.__matriz_mult(self,None,otro)
      elif(isinstance(otro, Matriz)):
        return self.__matriz_mult(self,otro)
      else:
        raise TypeError("Favor de proporcionar tipos de valores validos.")

  def __rmul__(self,otro):
      self.__verificar_matriz_mult(otro,self)
      if(isinstance(otro, int)):
        return self.__matriz_mult(self,None,otro)
      elif(isinstance(otro, Matriz)):
        return self.__matriz_mult(otro,self)
      else:
        return self.__matriz_mult(otro);

  def __add__(self,otro):
    if(self.n != otro.n or self.m != otro.m) :
      raise TypeError("No seas menso, si no son de la misma dimensión las matrices no se pueden sumar")
    resultado = [[0 for _ in range(self.m)] for _ in range(self.n)]
    for i in range(0,self.n,1):
      for j in range(0,self.m,1):
        resultado[i][j] += self.matriz[i][j] + otro.matriz[i][j]
    return Matriz(array=resultado)










In [ ]:
# Realiza las pruebas a la clase aquí

A = Matriz(n=3, m=4)
print('A =', A)

A = Matriz(n=5, m=5,tipo='diag')
A = A.quitacolumna(5)
print('A = ', A)

B = Matriz(4,4,'diag')
print('B = ', B)

C = Matriz(4,1,'unos')
print('C =', C)

D = 3 * B * C
print('D = ', D)

E = 3 * B + D
print('E = ', E)

A = 
0 0 0 0 
0 0 0 0 
0 0 0 0 

A =  
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 
0 0 0 0 

B =  
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 

C = 
1 
1 
1 
1 

D =  
3 0 0 0 
3 0 0 0 
3 0 0 0 
3 0 0 0 

E =  
6 0 0 0 
3 3 0 0 
3 0 3 0 
3 0 0 3 



## **Manejo de errores**

In [ ]:
#DIAGONAL NO VALIDA
A = Matriz(n=3, m=4, tipo="diag")
print('A =', A)

TypeError: Diagonal no válida. Para poder hacer una diagonal tiene que ser una matriz cuadrada.

In [ ]:
#MULTIPLICACION NO VALIDA POR DIMENSIONES NO COMPATIBLES
A * B

TypeError: Multiplicación no válida. Las columnas de la primera matriz no son iguales a las filas de la segunda matriz.

In [ ]:
#ERROR MULTIPLICACION DE TIPOS
A * "STRING"

TypeError: Favor de proporcionar tipos de valaores valaidos.

In [ ]:
#ERROR SUMA
A + B

TypeError: No seas menso, si no son de la misma dimensión las matrices no se pueden sumar